server:
  port: 8080

spring:
  application:
    name: ordinate-api
  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info